management:
  zipkin:
    tracing:
      endpoint:  http://zipkin:9411/
    sampling:
      probability: 1.0
spring:
  datasource:
    url: jdbc:mariadb://database:3306/auth
    username: root
    password: R0Oto!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      authorizationserver:
        issuer: https://auth.mrakaki.com
        client:
          frontend:
            registration:
              client-id: frontend
              client-secret: "{noop}secret"
              client-name: Frontend client
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
                - client_credentials
              redirect-uris:
                - https://eve.mrakaki.com/login/oauth2/code/frontend-oidc
                - https://eve.mrakaki.com/authorized
              scopes:
                - "openid"
                - "profile"
rsa:
  key-id: 7e5e1f47-35d4-4b3b-a4c8-0a3f0bc8bf9c
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
admin:
  username: admin
  password: ADMIN!