management:
  zipkin:
    tracing:
      endpoint:  http://localhost:9411/api/v2/spans
    sampling:
      probability: 1.0
server:
  port:
    10001
spring:
  datasource:
    url: jdbc:h2:file:./auth-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;DB_CLOSE_DELAY=-1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      authorizationserver:
        issuer: http://auth:10001
        client:
          frontend:
            registration:
              client-id: frontend
              client-secret: "{noop}secret"
              client-name: Frontend client
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
                - client_credentials
              redirect-uris:
                - http://localhost:10000/login/oauth2/code/frontend-oidc
                - http://lcoalhost:10000/authorized
                - https://oauthdebugger.com/debug
              scopes:
                - "openid"
                - "profile"
rsa:
  key-id: 7e5e1f47-35d4-4b3b-a4c8-0a3f0bc8bf9c
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
admin:
  username: admin
  password: ADMIN!