management:
  zipkin:
    tracing:
      endpoint:  http://localhost:9411/api/v2/spans
    sampling:
      probability: 1.0
  server:
    port: 2023
  health:
    probes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
logging:
  level:
    org.springframework.security: trace
server:
  port:
    10001
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/auth
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:migrations
    baseline-on-migrate: true
    validate-on-migrate: true
  security:
    oauth2:
      client:
        registration:
          eve:
            provider: eve
            client-id: 2dad4cfd4e424d62a92733add96168b9
            client-secret: g9y0H4jzqWdmtjBfVTi0ipyPptEOo8anOjcWlgzU
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/eve"
            scope:
              - publicData
              - esi-markets.structure_markets.v1
        provider:
          eve:
            authorization-uri: https://login.eveonline.com/v2/oauth/authorize
            token-uri: https://login.eveonline.com/v2/oauth/token
            jwk-set-uri: https://login.eveonline.com/oauth/jwks
            user-info-uri: "nope"
      authorizationserver:
        issuer: http://auth:10001
        client:
          buyback_frontend:
            registration:
              client-id: buyback
              client-secret: "{noop}secret"
              client-name: Buyback client
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
                - client_credentials
              redirect-uris:
                - http://localhost:10000/login/oauth2/code/buyback-oidc
                - http://localhost:10000/login/oauth2/code/buyback-markets
                - http://lcoalhost:10000/authorized
                - https://oauthdebugger.com/debug
              scopes:
                - "openid"
                - "profile"
                - esi-markets.structure_markets.v1
rsa:
  key-id: 7e5e1f47-35d4-4b3b-a4c8-0a3f0bc8bf9c
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
communication:
  token: asdgnkl98024y8723sd
