management:
  zipkin:
    tracing:
      endpoint:  http://zipkin:9411/api/v2/spans
    sampling:
      probability: 1.0
  server:
    port: 2022
  health:
    probes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
spring:
  datasource:
    url: jdbc:mariadb://10.0.11.49:3306/buyback
    username: eve_app
    password: R0Oto!
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:migrations
    baseline-on-migrate: true
    validate-on-migrate: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.mrakaki.com

endpoints:
  universe: http://universe:8080