spring:
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:file:./buyback-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;DB_CLOSE_DELAY=-1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth:10001
management:
  zipkin:
    tracing:
      endpoint:  http://localhost:9411/api/v2/spans
    sampling:
      probability: 1.0
server:
  port: 10004

logging:
  level:
    org.springframework.security: trace

endpoints:
  itemDetails: http://localhost:10003
  itemPrice: http://localhost:10002