management:
  zipkin:
    tracing:
      endpoint:  http://zipkin:9411/api/v2/spans
    sampling:
      probability: 1.0
spring:
  security:
    oauth2:
      client:
        registration:
          buyback_frontend-oidc:
            provider: spring
            client-id: buyback_frontend
            client-secret: secret
            authorization-grant-type:
              - authorization_code
              - client_credentials
            redirect-uri: "https://buyback.mrakaki.com/login/oauth2/code/buyback_frontend-oidc"
            scope: openid
            client-name: frontend-oidc
          buyback_frontend-authorization-code:
            provider: spring
            client-id: buyback_frontend
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "https://buyback.mrakaki.com/authorized"
            scope: openid
            client-name: buyback_frontend-authorization-code
        provider:
          spring:
            issuer-uri: https://auth.mrakaki.com
endpoints:
  universe: http://universe:8080
  buyback: http://buyback-backend:8080