spring:
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:file:./prices-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;DB_CLOSE_DELAY=-1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:10001
management:
  zipkin:
    tracing:
      endpoint:  http://localhost:9411/api/v2/spans
    sampling:
      probability: 1.0
server:
  port: 10002

logging:
  level:
    org.springframework.security: trace
janice:
  apiKey: Kd12YwNhL1TkcvmqDsk7UghrX7OIOx8O
