management:
  zipkin:
    tracing:
      endpoint:  http://zipkin:9411/api/v2/spans
    sampling:
      probability: 1.0
spring:
  datasource:
    url: jdbc:mariadb://10.0.11.49:3306/universe
    username: eve_app
    password: R0Oto!
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:migrations
    baseline-on-migrate: true
    validate-on-migrate: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.mrakaki.com

endpoints:
  itemDetails: http://item-detail:8080
  itemPrice: http://item-price:8080
  eve:
    api: https://esi.evetech.net/latest
    bsd: https://eve-static-data-export.s3-eu-west-1.amazonaws.com/tranquility/bsd.zip
    fsd: https://eve-static-data-export.s3-eu-west-1.amazonaws.com/tranquility/fsd.zip
communication:
  token: asdgnkl98024y8723sd
  authEnpoint: https://auth.mrakaki.com