spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/universe
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth:10001
management:
  zipkin:
    tracing:
      endpoint:  http://localhost:9411/api/v2/spans
    sampling:
      probability: 1.0
server:
  port: 10002

endpoints:
  itemDetails: http://localhost:10003
  itemPrice: http://localhost:10002